export const SET_OFFERS_DATA = 'SET_OFFERS_DATA';
export const SET_OFFER_DATA = 'SET_OFFER_DATA';
export const SET_OFFERS_IS_LOADED = 'SET_OFFERS_IS_LOADED';
export const SET_OFFERS_IS_LOADING = 'SET_OFFERS_IS_LOADING';
